version: 2.1
# orbs - reusable packages for our application
orbs: 
  node: circleci/openjdk:17.0.7
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
  #considered a 3rd party orb
  #jobs - set of instructions / functions
jobs:
  build: # job name
    docker: #environment
      - image: cimg/openjdk:17-jdk
    steps: 
      - checkout
      - java/install-jdk:
          version: 17
      - run: |
          echo "Building Spring Boot application..."
          ./mvnw package -DskipTests=true
  test:
    docker:
      - image: cimg/openjdk:17-jdk
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run Tests and rebuild the project
          command: ./mvnw test
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: whlionel704/education-space
      - docker/push:
          image: whlionel704/education-space
  
  scan:
    docker:
      - image: cimg/openjdk:17-jdk
    environment: 
      IMAGE_NAME: whlionel704/education-space
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

#workflow - defines what sequence will the jobs run
workflows:
  ci_workflow:
    jobs:
      - build:
        filters:
          branches:
            only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main
      - publish:
          requires:
            - test
          filters:
            branches:
              only: develop
