version: 2.1
# orbs - reusable packages for our application
orbs: 
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
  heroku: circleci/heroku@2.0.0
  #considered a 3rd party orb
  #jobs - set of instructions / functions
jobs:
  build: # job name
    docker: #environment
      - image: cimg/openjdk:19.0.1
    steps: 
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: whlionel704/circleci-project5:v3
      - docker/push:
          image: whlionel704/circleci-project5:v3
  
  scan:
    docker:
      - image: cimg/openjdk:17-jdk
    environment: 
      IMAGE_NAME: whlionel704/circleci-project5:v3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
    
    deploy:
      docker:
        - image: cimg/openjdk:19.0.1
      steps:
        - setup_remote_docker
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: |
              heroku container:login
              heroku container:push web -a circleci-project5
              heroku container:release web -a circleci-project5

#workflow - defines what sequence will the jobs run
workflows:
  ci_cd_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - develop
                - release
      - scan:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
                - release
      - publish:
          requires:
            - build
          filters:
            branches:
              only: release

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release

