version: 2.1
# orbs - reusable packages for our application
orbs: 
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
  #considered a 3rd party orb
  #jobs - set of instructions / functions
jobs:
  build: # job name
    docker: #environment
      - image: cimg/openjdk:19.0.1
    steps: 
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: whlionel704/circleci-project5:v3
      - docker/push:
          image: whlionel704/circleci-project5:v3
  
  scan:
    docker:
      - image: cimg/openjdk:17-jdk
    environment: 
      IMAGE_NAME: whlionel704/circleci-project5:v3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

#workflow - defines what sequence will the jobs run
workflows:
  ci_workflow:
    jobs:
      - build:
        filters:
          branches:
            only: main
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main
      - publish:
          filters:
            branches:
              only: develop
